
/* Drop Tables */

DROP TABLE CHATBOT CASCADE CONSTRAINTS;
DROP TABLE EVENT CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE QNA CASCADE CONSTRAINTS;
DROP TABLE ADMIN CASCADE CONSTRAINTS;
DROP TABLE BUY CASCADE CONSTRAINTS;
DROP TABLE CARTDETAIL CASCADE CONSTRAINTS;
DROP TABLE CART CASCADE CONSTRAINTS;
DROP TABLE COMMENTS CASCADE CONSTRAINTS;
DROP TABLE CYBERMONEY CASCADE CONSTRAINTS;
DROP TABLE EVENT_ALERT CASCADE CONSTRAINTS;
DROP TABLE FAQ CASCADE CONSTRAINTS;
DROP TABLE FRIEND CASCADE CONSTRAINTS;
DROP TABLE FRIEND_REQ_LIST CASCADE CONSTRAINTS;
DROP TABLE GUESTBOOK CASCADE CONSTRAINTS;
DROP TABLE HOMPI_DESIGN CASCADE CONSTRAINTS;
DROP TABLE POST CASCADE CONSTRAINTS;
DROP TABLE HOMPI CASCADE CONSTRAINTS;
DROP TABLE ITEM_COLLECTION CASCADE CONSTRAINTS;
DROP TABLE ITEM CASCADE CONSTRAINTS;
DROP TABLE LFAQ CASCADE CONSTRAINTS;
DROP TABLE LITEM CASCADE CONSTRAINTS;
DROP TABLE MINIMI_COLLECTION CASCADE CONSTRAINTS;
DROP TABLE MINIMI CASCADE CONSTRAINTS;
DROP TABLE LMINIMI CASCADE CONSTRAINTS;
DROP TABLE MUSIC_COLLECTION CASCADE CONSTRAINTS;
DROP TABLE MUSIC CASCADE CONSTRAINTS;
DROP TABLE LMUSIC CASCADE CONSTRAINTS;
DROP TABLE LPOST CASCADE CONSTRAINTS;
DROP TABLE MESSAGE CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;




/* Create Tables */

-- 관리자
CREATE TABLE ADMIN
(
	-- 관리자 ID
	ADMIN_ID varchar2(15) NOT NULL,
	-- 작성자 이름 : 작성자 이름
	NOTICE_WRITER varchar2(60),
	-- 관리자 비밀번호
	ADMIN_PASS varchar2(15),
	-- 관리자 닉네임
	ADMIN_NICNAME varchar2(60),
	PRIMARY KEY (ADMIN_ID)
);


-- 구매
CREATE TABLE BUY
(
	-- 구매 ID : 구매 ID
	BUY_ID char(13) NOT NULL,
	-- 장바구니 ID
	CART_ID varchar2(13) NOT NULL,
	-- 회원 ID : 회원 ID
	MEM_ID varchar2(15),
	-- 구매 금액 : 구매 금액
	-- 
	BUY_COST number(10,0),
	-- 구매 상태 : 구매 상태
	BUY_STATUS varchar2(15),
	-- 구매 일시 : 구매 일시
	BUY_DATE date,
	PRIMARY KEY (BUY_ID)
);


-- 장바구니
CREATE TABLE CART
(
	-- 장바구니 ID
	CART_ID varchar2(13) NOT NULL,
	-- 회원 ID
	MEM_ID varchar2(15) NOT NULL,
	-- 장바구니 일자 : 장바구니 일자
	CART_DATE date,
	PRIMARY KEY (CART_ID)
);


-- 장바구니상세
CREATE TABLE CARTDETAIL
(
	-- 장바구니 상세 번호
	CARTDETAIL_NO char(15) NOT NULL,
	-- 장바구니 ID
	CART_ID varchar2(13) NOT NULL,
	-- 음원 ID
	MUSIC_ID varchar2(10) NOT NULL,
	-- 아이템 ID
	ITEM_ID varchar2(15) NOT NULL,
	-- 장바구니 상품 수량
	CART_QTY number(5,0),
	PRIMARY KEY (CARTDETAIL_NO)
);


-- 챗봇
CREATE TABLE CHATBOT
(
	-- 챗봇 순번
	CHATBOT_NO varchar2(10) NOT NULL,
	-- 관리자 ID
	ADMIN_ID varchar2(15) NOT NULL,
	-- 회원 ID
	MEM_ID varchar2(15) NOT NULL,
	-- 챗봇 메시지 : 챗봇 메시지
	CHATBOT_MSG varchar2(4000),
	-- 회원 메시지
	MEM_MSG varchar2(100),
	PRIMARY KEY (CHATBOT_NO)
);


-- 댓글
CREATE TABLE COMMENTS
(
	-- 홈피게시판 번호
	POST_NO varchar2(15) NOT NULL,
	-- 회원 ID
	MEM_ID varchar2(15) NOT NULL,
	-- 댓글 내용
	COMMENTS_CONTENT varchar2(300),
	-- 댓글 작성시간 : 댓글 작성시간
	COMMENTS_DATE date
);


-- 사이버머니
CREATE TABLE CYBERMONEY
(
	-- 순번
	CYBERMONEY_NO varchar2(10) NOT NULL,
	-- 회원 ID
	MEM_ID varchar2(15) NOT NULL,
	-- 사이버머니_잔고 : 사이버머니 잔고
	CYBERMONEY_BALANCE varchar2(15),
	-- 사이버머니 변동사항
	CYBERMONEY_STATUS varchar2(15),
	PRIMARY KEY (CYBERMONEY_NO)
);


-- 이벤트
CREATE TABLE EVENT
(
	-- 이벤트 번호
	EVENT_NO char(15) NOT NULL,
	-- 관리자 ID
	ADMIN_ID varchar2(15) NOT NULL,
	-- 이벤트 제목
	EVENT_TITLE varchar2(60),
	-- 이벤트 내용 : 이벤트 내용
	EVENT_CONTENT varchar2(4000),
	-- 이벤트 첨부파일 : 이벤트 첨부파일
	EVENT_ATTACHMENTS varchar2(4000),
	-- 이벤트 작성일 : 이벤트작성일
	EVENT_DATE date,
	PRIMARY KEY (EVENT_NO)
);


-- 알림
CREATE TABLE EVENT_ALERT
(
	-- 알림ID : 알림ID
	ALERT_ID varchar2(30) NOT NULL,
	-- 회원 ID
	MEM_ID varchar2(15) NOT NULL,
	-- 알림 내용 : 알림 내용
	ALERT_CONTENT varchar2(4000) NOT NULL,
	PRIMARY KEY (ALERT_ID)
);


-- 자주묻는질문
CREATE TABLE FAQ
(
	-- 자주묻는질문 ID
	FAQ_ID varchar2(10) NOT NULL,
	-- 자주묻는질문 분류 코드
	LFAQ_GU char(15) NOT NULL,
	-- 자주묻는질문 제목
	FAQ_TITLE varchar2(30),
	-- 자주묻는질문 내용
	FAQ_CONTENT clob,
	PRIMARY KEY (FAQ_ID)
);


-- 일촌
CREATE TABLE FRIEND
(
	-- 일촌 ID : 일촌 ID
	FRIEND_ID varchar2(15) NOT NULL,
	-- 회원 ID : 회원 ID
	MEM_ID varchar2(15) NOT NULL,
	-- 친구등록일자 : 친구등록일자
	FRIEND_DATE date NOT NULL,
	PRIMARY KEY (FRIEND_ID)
);


-- 일촌 신청목록
CREATE TABLE FRIEND_REQ_LIST
(
	-- 회원 ID : 회원 ID
	MEM_ID varchar2(15) NOT NULL,
	-- 일촌 ID : 일촌 ID
	FRIEND_ID varchar2(15) NOT NULL,
	-- 신청 날짜 : 신청 날짜
	REQ_DATE date,
	-- 수락 여부 : 수락 여부
	REQ_YN varchar2(1),
	PRIMARY KEY (MEM_ID, FRIEND_ID)
);


-- 방명록
CREATE TABLE GUESTBOOK
(
	-- 방명록 번호
	GUESTBOOK_NO varchar2(10) NOT NULL,
	-- 미니홈피 ID
	HOMPI_ID char(15) NOT NULL,
	-- 방명록 제목 : 방명록 제목
	GUESTBOOK_TITLE varchar2(60),
	-- 방명록 내용
	GUESTBOOK_CONTENT varchar2(300),
	-- 방명록 작성자
	GUSETBOOK_WRITER varchar2(100),
	-- 방명록 작성일
	GUESTBOOK_DATE date,
	PRIMARY KEY (GUESTBOOK_NO)
);


-- 미니홈피
CREATE TABLE HOMPI
(
	-- 미니홈피 ID
	HOMPI_ID char(15) NOT NULL,
	-- 회원 ID
	MEM_ID varchar2(15) NOT NULL,
	-- 방문횟수 : 방문횟수
	VISIT_COUNT number(5,0),
	-- 누적 방문 횟수 : 누적 방문 횟수
	VISIT_COUNT_TOT number(7),
	-- 스크랩 수 : 스크랩 수
	SCRAP_COUNT number(7),
	-- 홈피_소개 : 홈피_소개
	HOMPI_INFO varchar2(300),
	-- 홈피 공개범위 : 홈피 공개범위
	HOMPI_SET_PRIVACY number,
	PRIMARY KEY (HOMPI_ID)
);


-- 홈피디자인
CREATE TABLE HOMPI_DESIGN
(
	-- 미니홈피 ID
	HOMPI_ID char(15) NOT NULL,
	-- 배경속성 : 배경속성
	BACKGROUND_ATTR varchar2(30),
	-- 테두리 테마 : 테두리 테마
	BORDER_THEME varchar2(30),
	-- 메뉴 테두리 : 메뉴 테마
	MENU_BORDER varchar2(30),
	-- 메뉴 배경 : 메뉴 배경
	MENU_BACKGROUND varchar2(30),
	-- 메뉴 글자색 : 메뉴 글자색
	MENU_TXTCOLOR varchar2(30),
	-- 배경 음악 : 배경 음악
	BACKGROUND_MUSIC varchar2(30),
	-- 미니미 ID : 미니미
	MINIMI_ID varchar2(15),
	PRIMARY KEY (HOMPI_ID)
);


-- 아이템
CREATE TABLE ITEM
(
	-- 아이템 ID
	ITEM_ID varchar2(15) NOT NULL,
	-- 아이템 분류 코드
	LITEM_GU char(15) NOT NULL,
	-- 아이템 명
	ITEM_NAME varchar2(60),
	-- 아이템 설명 : 아이템 설명
	ITEM_DESC varchar2(4000),
	-- 아이템 가격
	ITEM_PRICE number(10,0),
	-- 아이템 재고 수량
	ITEM_TOTALSTOCK number(5,0),
	-- 아이템 이미지
	ITEM_IMG varchar2(1000),
	-- 아이템 정보 : 아이템 정보
	ITEM_DETAIL varchar2(1000),
	PRIMARY KEY (ITEM_ID)
);


-- 아이템 보유 목록
CREATE TABLE ITEM_COLLECTION
(
	-- 회원 ID
	MEM_ID varchar2(15) NOT NULL,
	-- 아이템 ID
	ITEM_ID varchar2(15) NOT NULL,
	PRIMARY KEY (MEM_ID, ITEM_ID)
);


-- 자주묻는질문 분류
CREATE TABLE LFAQ
(
	-- 자주묻는질문 분류 코드
	LFAQ_GU char(15) NOT NULL,
	-- 자주묻는질문 분류 명
	LFAQ_NM varchar2(30),
	PRIMARY KEY (LFAQ_GU)
);


-- 아이템 분류 정보
CREATE TABLE LITEM
(
	-- 아이템 분류 코드
	LITEM_GU char(15) NOT NULL,
	-- 아이템 분류 순번
	LITEM_NO number(5,0) NOT NULL,
	-- 아이템 분류 명
	LITEM_NM varchar2(30),
	PRIMARY KEY (LITEM_GU)
);


-- 미니미 분류 정보
CREATE TABLE LMINIMI
(
	-- 미니미 분류 코드 : 미니미 분류 코드
	LMINIMI_GU varchar2(30) NOT NULL,
	-- 미니미 분류 순번 : 미니미 분류 순번
	LMINIMI_NO number(5,0) NOT NULL,
	-- 미니미 분류 명 : 미니미 분류 명
	LMINIMI_NM varchar2(30),
	PRIMARY KEY (LMINIMI_GU)
);


-- 음원 장르 정보
CREATE TABLE LMUSIC
(
	-- 음원 장르 순번
	LMUSIC_NO number(5,0) NOT NULL,
	-- 음원 장르 코드
	LMUSIC_GU varchar2(15) NOT NULL,
	-- 음원 장르명
	LMUSIC_GENRE varchar2(30),
	PRIMARY KEY (LMUSIC_GU)
);


-- 홈피게시판 분류 정보
CREATE TABLE LPOST
(
	-- 홈피게시판 분류 코드
	LPOST_GU char(15) NOT NULL,
	-- 홈피게시판 분류 순번
	LPOST_NO number(5,0),
	-- 홈피게시판 분류 명
	LPOST_NM varchar2(30),
	PRIMARY KEY (LPOST_GU)
);


-- 회원
CREATE TABLE MEMBER
(
	-- 회원 ID
	MEM_ID varchar2(15) NOT NULL,
	-- 회원 비밀번호
	MEM_PASS varchar2(15),
	-- 회원 이름
	MEM_NAME varchar2(90),
	-- 회원 닉네임
	MEM_NICKNAME varchar2(30),
	-- 회원 성별
	MEM_GENDER varchar2(9),
	-- 회원 생일
	MEM_BIR date,
	-- 회원 우편번호
	MEM_ZIP char(7),
	-- 회원 기본 주소
	MEM_ADD1 varchar2(100),
	-- 회원 상세 주소
	MEM_ADD2 varchar2(80),
	-- 회원 이동 전화
	MEM_HP varchar2(15),
	-- 회원 이메일 주소
	MEM_MAIL varchar2(60),
	-- 회원 보유 사이버머니
	MEM_CYBERMONEY number(10,0),
	PRIMARY KEY (MEM_ID)
);


-- 쪽지
CREATE TABLE MESSAGE
(
	-- 쪽지번호 : 쪽지번호
	MESSAGE_NO number NOT NULL,
	-- 회원 ID
	MEM_ID varchar2(15) NOT NULL,
	-- 받은 회원 : 받은 회원
	RECEIVE_MEM varchar2(60),
	-- 쪽지내용 : 쪽지내용
	MESSAGE_CONTENT varchar2(200),
	-- 쪽지날짜 : 쪽지날짜
	MESSAGE_DATE date,
	PRIMARY KEY (MESSAGE_NO)
);


-- 미니미
CREATE TABLE MINIMI
(
	-- 미니미 ID : 미니미 ID
	MINIMI_ID varchar2(15) NOT NULL,
	-- 미니미 분류 코드 : 미니미 분류 코드
	LMINIMI_GU varchar2(30) NOT NULL,
	-- 미니미 명 : 미니미 명
	MINIMI_NAME varchar2(60) NOT NULL,
	-- 미니미 설명 : 미니미 설명
	MINIMI_DESC varchar2(4000),
	-- 미니미 가격 : 미니미 가격
	MINIMI_PRICE number(10),
	-- 미니미 이미지 : 미니미 이미지
	MINIMI_IMG varchar2(1000),
	-- 미니미 정보 : 미니미 정보
	MINIMI_DETAIL varchar2(1000),
	PRIMARY KEY (MINIMI_ID)
);


-- 미니미 보유목록
CREATE TABLE MINIMI_COLLECTION
(
	-- 회원 ID
	MEM_ID varchar2(15) NOT NULL,
	-- 미니미 ID : 미니미 ID
	MINIMI_ID varchar2(15) NOT NULL,
	PRIMARY KEY (MEM_ID, MINIMI_ID)
);


-- 음원
CREATE TABLE MUSIC
(
	-- 음원 ID
	MUSIC_ID varchar2(10) NOT NULL,
	-- 음원 장르 코드
	LMUSIC_GU varchar2(15) NOT NULL,
	-- 음원 제목
	MUSIC_TITLE varchar2(60),
	-- 음원 상세 : 음원 상세
	MUSIC_DESC varchar2(4000),
	-- 음원 가수
	MUSIC_ARTIST varchar2(60),
	-- 음원 작곡가
	MUSIC_COMPOSER varchar2(60),
	-- 음원 작사가
	MUSIC_LYRICIST varchar2(60),
	-- 음원 제작사
	MUSIC_COMPANY varchar2(60),
	-- 음원 제작년도
	MUSIC_YEAR number(4,0),
	-- 음원 앨범
	MUSIC_ALBUM varchar2(60),
	-- 음원 경로 : 음원 경로
	MUSIC_PATH varchar2(500) NOT NULL,
	-- 음원 가격 : 음원 가격
	MUSIC_COST number,
	PRIMARY KEY (MUSIC_ID)
);


-- 음반 보유 목록
CREATE TABLE MUSIC_COLLECTION
(
	-- 회원 ID
	MEM_ID varchar2(15) NOT NULL,
	-- 음원 ID
	MUSIC_ID varchar2(10) NOT NULL,
	PRIMARY KEY (MEM_ID, MUSIC_ID)
);


-- 공지게시판
CREATE TABLE NOTICE
(
	-- 공지게시판 번호
	NOTICE_NO char(15) NOT NULL,
	-- 관리자 ID
	ADMIN_ID varchar2(15) NOT NULL,
	-- 공지게시판 제목
	NOTICE_TITLE varchar2(60),
	-- 공지게시판 내용
	NOTICE_CONTENT varchar2(4000),
	-- 공지게시글 작성일
	NOTICE_DATE date,
	PRIMARY KEY (NOTICE_NO)
);


-- 홈피게시판
CREATE TABLE POST
(
	-- 홈피게시판 번호
	POST_NO varchar2(15) NOT NULL,
	-- 미니홈피 ID
	HOMPI_ID char(15) NOT NULL,
	-- 홈피게시판 분류 코드
	LPOST_GU char(15) NOT NULL,
	-- 회원 ID
	MEM_ID varchar2(15) NOT NULL,
	-- 홈피게시판 제목
	POST_TITLE varchar2(60),
	-- 홈피게시판 내용
	POST_CONTENT clob,
	-- 홈피게시판 첨부파일
	POST_ATTACHMENTS clob,
	-- 게시글 작성일 : 게시글 작성일
	POST_DATE date,
	-- 게시글 조회수 : 게시글 조회수
	POST_VIEW number,
	PRIMARY KEY (POST_NO)
);


-- 1대1문의
CREATE TABLE QNA
(
	-- 1대1문의 번호
	QNA_NO char(15) NOT NULL,
	-- 회원 ID
	MEM_ID varchar2(15) NOT NULL,
	-- 관리자 ID
	ADMIN_ID varchar2(15) NOT NULL,
	-- 1대1문의 제목
	QNA_TITLE varchar2(60),
	-- 1대1문의 내용 : 1대1문의 내용
	QNA_CONTENT varchar2(4000),
	-- 1대1문의 첨부파일 : 1대1문의 첨부파일
	QNA_ATTACHMENTS varchar2(4000),
	-- 1대1문의 작성일 : 1대1문의작성일
	QNA_DATE date,
	-- 1대1문의 답변 : 1대1문의 답변
	QNA_RESULT varchar2(4000),
	-- 1대1문의 카테고리 : 1대1 문의 카테고리
	QNA_CATEGORY varchar2(60) NOT NULL,
	PRIMARY KEY (QNA_NO)
);



/* Create Foreign Keys */

ALTER TABLE CHATBOT
	ADD FOREIGN KEY (ADMIN_ID)
	REFERENCES ADMIN (ADMIN_ID)
;


ALTER TABLE EVENT
	ADD FOREIGN KEY (ADMIN_ID)
	REFERENCES ADMIN (ADMIN_ID)
;


ALTER TABLE NOTICE
	ADD FOREIGN KEY (ADMIN_ID)
	REFERENCES ADMIN (ADMIN_ID)
;


ALTER TABLE QNA
	ADD FOREIGN KEY (ADMIN_ID)
	REFERENCES ADMIN (ADMIN_ID)
;


ALTER TABLE BUY
	ADD FOREIGN KEY (CART_ID)
	REFERENCES CART (CART_ID)
;


ALTER TABLE CARTDETAIL
	ADD FOREIGN KEY (CART_ID)
	REFERENCES CART (CART_ID)
;


ALTER TABLE FRIEND
	ADD FOREIGN KEY (FRIEND_ID, MEM_ID)
	REFERENCES FRIEND_REQ_LIST (FRIEND_ID, MEM_ID)
;


ALTER TABLE GUESTBOOK
	ADD FOREIGN KEY (HOMPI_ID)
	REFERENCES HOMPI (HOMPI_ID)
;


ALTER TABLE HOMPI_DESIGN
	ADD FOREIGN KEY (HOMPI_ID)
	REFERENCES HOMPI (HOMPI_ID)
;


ALTER TABLE POST
	ADD FOREIGN KEY (HOMPI_ID)
	REFERENCES HOMPI (HOMPI_ID)
;


ALTER TABLE CARTDETAIL
	ADD FOREIGN KEY (ITEM_ID)
	REFERENCES ITEM (ITEM_ID)
;


ALTER TABLE ITEM_COLLECTION
	ADD FOREIGN KEY (ITEM_ID)
	REFERENCES ITEM (ITEM_ID)
;


ALTER TABLE FAQ
	ADD FOREIGN KEY (LFAQ_GU)
	REFERENCES LFAQ (LFAQ_GU)
;


ALTER TABLE ITEM
	ADD FOREIGN KEY (LITEM_GU)
	REFERENCES LITEM (LITEM_GU)
;


ALTER TABLE MINIMI
	ADD FOREIGN KEY (LMINIMI_GU)
	REFERENCES LMINIMI (LMINIMI_GU)
;


ALTER TABLE MUSIC
	ADD FOREIGN KEY (LMUSIC_GU)
	REFERENCES LMUSIC (LMUSIC_GU)
;


ALTER TABLE POST
	ADD FOREIGN KEY (LPOST_GU)
	REFERENCES LPOST (LPOST_GU)
;


ALTER TABLE CART
	ADD FOREIGN KEY (MEM_ID)
	REFERENCES MEMBER (MEM_ID)
;


ALTER TABLE CHATBOT
	ADD FOREIGN KEY (MEM_ID)
	REFERENCES MEMBER (MEM_ID)
;


ALTER TABLE COMMENTS
	ADD FOREIGN KEY (MEM_ID)
	REFERENCES MEMBER (MEM_ID)
;


ALTER TABLE CYBERMONEY
	ADD FOREIGN KEY (MEM_ID)
	REFERENCES MEMBER (MEM_ID)
;


ALTER TABLE EVENT_ALERT
	ADD FOREIGN KEY (MEM_ID)
	REFERENCES MEMBER (MEM_ID)
;


ALTER TABLE FRIEND_REQ_LIST
	ADD FOREIGN KEY (MEM_ID)
	REFERENCES MEMBER (MEM_ID)
;


ALTER TABLE HOMPI
	ADD FOREIGN KEY (MEM_ID)
	REFERENCES MEMBER (MEM_ID)
;


ALTER TABLE ITEM_COLLECTION
	ADD FOREIGN KEY (MEM_ID)
	REFERENCES MEMBER (MEM_ID)
;


ALTER TABLE MESSAGE
	ADD FOREIGN KEY (MEM_ID)
	REFERENCES MEMBER (MEM_ID)
;


ALTER TABLE MINIMI_COLLECTION
	ADD FOREIGN KEY (MEM_ID)
	REFERENCES MEMBER (MEM_ID)
;


ALTER TABLE MUSIC_COLLECTION
	ADD FOREIGN KEY (MEM_ID)
	REFERENCES MEMBER (MEM_ID)
;


ALTER TABLE POST
	ADD FOREIGN KEY (MEM_ID)
	REFERENCES MEMBER (MEM_ID)
;


ALTER TABLE QNA
	ADD FOREIGN KEY (MEM_ID)
	REFERENCES MEMBER (MEM_ID)
;


ALTER TABLE MINIMI_COLLECTION
	ADD FOREIGN KEY (MINIMI_ID)
	REFERENCES MINIMI (MINIMI_ID)
;


ALTER TABLE CARTDETAIL
	ADD FOREIGN KEY (MUSIC_ID)
	REFERENCES MUSIC (MUSIC_ID)
;


ALTER TABLE MUSIC_COLLECTION
	ADD FOREIGN KEY (MUSIC_ID)
	REFERENCES MUSIC (MUSIC_ID)
;


ALTER TABLE COMMENTS
	ADD FOREIGN KEY (POST_NO)
	REFERENCES POST (POST_NO)
;



/* Comments */

COMMENT ON TABLE ADMIN IS '관리자';
COMMENT ON COLUMN ADMIN.ADMIN_ID IS '관리자 ID';
COMMENT ON COLUMN ADMIN.NOTICE_WRITER IS '작성자 이름 : 작성자 이름';
COMMENT ON COLUMN ADMIN.ADMIN_PASS IS '관리자 비밀번호';
COMMENT ON COLUMN ADMIN.ADMIN_NICNAME IS '관리자 닉네임';
COMMENT ON TABLE BUY IS '구매';
COMMENT ON COLUMN BUY.BUY_ID IS '구매 ID : 구매 ID';
COMMENT ON COLUMN BUY.CART_ID IS '장바구니 ID';
COMMENT ON COLUMN BUY.MEM_ID IS '회원 ID : 회원 ID';
COMMENT ON COLUMN BUY.BUY_COST IS '구매 금액 : 구매 금액
';
COMMENT ON COLUMN BUY.BUY_STATUS IS '구매 상태 : 구매 상태';
COMMENT ON COLUMN BUY.BUY_DATE IS '구매 일시 : 구매 일시';
COMMENT ON TABLE CART IS '장바구니';
COMMENT ON COLUMN CART.CART_ID IS '장바구니 ID';
COMMENT ON COLUMN CART.MEM_ID IS '회원 ID';
COMMENT ON COLUMN CART.CART_DATE IS '장바구니 일자 : 장바구니 일자';
COMMENT ON TABLE CARTDETAIL IS '장바구니상세';
COMMENT ON COLUMN CARTDETAIL.CARTDETAIL_NO IS '장바구니 상세 번호';
COMMENT ON COLUMN CARTDETAIL.CART_ID IS '장바구니 ID';
COMMENT ON COLUMN CARTDETAIL.MUSIC_ID IS '음원 ID';
COMMENT ON COLUMN CARTDETAIL.ITEM_ID IS '아이템 ID';
COMMENT ON COLUMN CARTDETAIL.CART_QTY IS '장바구니 상품 수량';
COMMENT ON TABLE CHATBOT IS '챗봇';
COMMENT ON COLUMN CHATBOT.CHATBOT_NO IS '챗봇 순번';
COMMENT ON COLUMN CHATBOT.ADMIN_ID IS '관리자 ID';
COMMENT ON COLUMN CHATBOT.MEM_ID IS '회원 ID';
COMMENT ON COLUMN CHATBOT.CHATBOT_MSG IS '챗봇 메시지 : 챗봇 메시지';
COMMENT ON COLUMN CHATBOT.MEM_MSG IS '회원 메시지';
COMMENT ON TABLE COMMENTS IS '댓글';
COMMENT ON COLUMN COMMENTS.POST_NO IS '홈피게시판 번호';
COMMENT ON COLUMN COMMENTS.MEM_ID IS '회원 ID';
COMMENT ON COLUMN COMMENTS.COMMENTS_CONTENT IS '댓글 내용';
COMMENT ON COLUMN COMMENTS.COMMENTS_DATE IS '댓글 작성시간 : 댓글 작성시간';
COMMENT ON TABLE CYBERMONEY IS '사이버머니';
COMMENT ON COLUMN CYBERMONEY.CYBERMONEY_NO IS '순번';
COMMENT ON COLUMN CYBERMONEY.MEM_ID IS '회원 ID';
COMMENT ON COLUMN CYBERMONEY.CYBERMONEY_BALANCE IS '사이버머니_잔고 : 사이버머니 잔고';
COMMENT ON COLUMN CYBERMONEY.CYBERMONEY_STATUS IS '사이버머니 변동사항';
COMMENT ON TABLE EVENT IS '이벤트';
COMMENT ON COLUMN EVENT.EVENT_NO IS '이벤트 번호';
COMMENT ON COLUMN EVENT.ADMIN_ID IS '관리자 ID';
COMMENT ON COLUMN EVENT.EVENT_TITLE IS '이벤트 제목';
COMMENT ON COLUMN EVENT.EVENT_CONTENT IS '이벤트 내용 : 이벤트 내용';
COMMENT ON COLUMN EVENT.EVENT_ATTACHMENTS IS '이벤트 첨부파일 : 이벤트 첨부파일';
COMMENT ON COLUMN EVENT.EVENT_DATE IS '이벤트 작성일 : 이벤트작성일';
COMMENT ON TABLE EVENT_ALERT IS '알림';
COMMENT ON COLUMN EVENT_ALERT.ALERT_ID IS '알림ID : 알림ID';
COMMENT ON COLUMN EVENT_ALERT.MEM_ID IS '회원 ID';
COMMENT ON COLUMN EVENT_ALERT.ALERT_CONTENT IS '알림 내용 : 알림 내용';
COMMENT ON TABLE FAQ IS '자주묻는질문';
COMMENT ON COLUMN FAQ.FAQ_ID IS '자주묻는질문 ID';
COMMENT ON COLUMN FAQ.LFAQ_GU IS '자주묻는질문 분류 코드';
COMMENT ON COLUMN FAQ.FAQ_TITLE IS '자주묻는질문 제목';
COMMENT ON COLUMN FAQ.FAQ_CONTENT IS '자주묻는질문 내용';
COMMENT ON TABLE FRIEND IS '일촌';
COMMENT ON COLUMN FRIEND.FRIEND_ID IS '일촌 ID : 일촌 ID';
COMMENT ON COLUMN FRIEND.MEM_ID IS '회원 ID : 회원 ID';
COMMENT ON COLUMN FRIEND.FRIEND_DATE IS '친구등록일자 : 친구등록일자';
COMMENT ON TABLE FRIEND_REQ_LIST IS '일촌 신청목록';
COMMENT ON COLUMN FRIEND_REQ_LIST.MEM_ID IS '회원 ID : 회원 ID';
COMMENT ON COLUMN FRIEND_REQ_LIST.FRIEND_ID IS '일촌 ID : 일촌 ID';
COMMENT ON COLUMN FRIEND_REQ_LIST.REQ_DATE IS '신청 날짜 : 신청 날짜';
COMMENT ON COLUMN FRIEND_REQ_LIST.REQ_YN IS '수락 여부 : 수락 여부';
COMMENT ON TABLE GUESTBOOK IS '방명록';
COMMENT ON COLUMN GUESTBOOK.GUESTBOOK_NO IS '방명록 번호';
COMMENT ON COLUMN GUESTBOOK.HOMPI_ID IS '미니홈피 ID';
COMMENT ON COLUMN GUESTBOOK.GUESTBOOK_TITLE IS '방명록 제목 : 방명록 제목';
COMMENT ON COLUMN GUESTBOOK.GUESTBOOK_CONTENT IS '방명록 내용';
COMMENT ON COLUMN GUESTBOOK.GUSETBOOK_WRITER IS '방명록 작성자';
COMMENT ON COLUMN GUESTBOOK.GUESTBOOK_DATE IS '방명록 작성일';
COMMENT ON TABLE HOMPI IS '미니홈피';
COMMENT ON COLUMN HOMPI.HOMPI_ID IS '미니홈피 ID';
COMMENT ON COLUMN HOMPI.MEM_ID IS '회원 ID';
COMMENT ON COLUMN HOMPI.VISIT_COUNT IS '방문횟수 : 방문횟수';
COMMENT ON COLUMN HOMPI.VISIT_COUNT_TOT IS '누적 방문 횟수 : 누적 방문 횟수';
COMMENT ON COLUMN HOMPI.SCRAP_COUNT IS '스크랩 수 : 스크랩 수';
COMMENT ON COLUMN HOMPI.HOMPI_INFO IS '홈피_소개 : 홈피_소개';
COMMENT ON COLUMN HOMPI.HOMPI_SET_PRIVACY IS '홈피 공개범위 : 홈피 공개범위';
COMMENT ON TABLE HOMPI_DESIGN IS '홈피디자인';
COMMENT ON COLUMN HOMPI_DESIGN.HOMPI_ID IS '미니홈피 ID';
COMMENT ON COLUMN HOMPI_DESIGN.BACKGROUND_ATTR IS '배경속성 : 배경속성';
COMMENT ON COLUMN HOMPI_DESIGN.BORDER_THEME IS '테두리 테마 : 테두리 테마';
COMMENT ON COLUMN HOMPI_DESIGN.MENU_BORDER IS '메뉴 테두리 : 메뉴 테마';
COMMENT ON COLUMN HOMPI_DESIGN.MENU_BACKGROUND IS '메뉴 배경 : 메뉴 배경';
COMMENT ON COLUMN HOMPI_DESIGN.MENU_TXTCOLOR IS '메뉴 글자색 : 메뉴 글자색';
COMMENT ON COLUMN HOMPI_DESIGN.BACKGROUND_MUSIC IS '배경 음악 : 배경 음악';
COMMENT ON COLUMN HOMPI_DESIGN.MINIMI_ID IS '미니미 ID : 미니미';
COMMENT ON TABLE ITEM IS '아이템';
COMMENT ON COLUMN ITEM.ITEM_ID IS '아이템 ID';
COMMENT ON COLUMN ITEM.LITEM_GU IS '아이템 분류 코드';
COMMENT ON COLUMN ITEM.ITEM_NAME IS '아이템 명';
COMMENT ON COLUMN ITEM.ITEM_DESC IS '아이템 설명 : 아이템 설명';
COMMENT ON COLUMN ITEM.ITEM_PRICE IS '아이템 가격';
COMMENT ON COLUMN ITEM.ITEM_TOTALSTOCK IS '아이템 재고 수량';
COMMENT ON COLUMN ITEM.ITEM_IMG IS '아이템 이미지';
COMMENT ON COLUMN ITEM.ITEM_DETAIL IS '아이템 정보 : 아이템 정보';
COMMENT ON TABLE ITEM_COLLECTION IS '아이템 보유 목록';
COMMENT ON COLUMN ITEM_COLLECTION.MEM_ID IS '회원 ID';
COMMENT ON COLUMN ITEM_COLLECTION.ITEM_ID IS '아이템 ID';
COMMENT ON TABLE LFAQ IS '자주묻는질문 분류';
COMMENT ON COLUMN LFAQ.LFAQ_GU IS '자주묻는질문 분류 코드';
COMMENT ON COLUMN LFAQ.LFAQ_NM IS '자주묻는질문 분류 명';
COMMENT ON TABLE LITEM IS '아이템 분류 정보';
COMMENT ON COLUMN LITEM.LITEM_GU IS '아이템 분류 코드';
COMMENT ON COLUMN LITEM.LITEM_NO IS '아이템 분류 순번';
COMMENT ON COLUMN LITEM.LITEM_NM IS '아이템 분류 명';
COMMENT ON TABLE LMINIMI IS '미니미 분류 정보';
COMMENT ON COLUMN LMINIMI.LMINIMI_GU IS '미니미 분류 코드 : 미니미 분류 코드';
COMMENT ON COLUMN LMINIMI.LMINIMI_NO IS '미니미 분류 순번 : 미니미 분류 순번';
COMMENT ON COLUMN LMINIMI.LMINIMI_NM IS '미니미 분류 명 : 미니미 분류 명';
COMMENT ON TABLE LMUSIC IS '음원 장르 정보';
COMMENT ON COLUMN LMUSIC.LMUSIC_NO IS '음원 장르 순번';
COMMENT ON COLUMN LMUSIC.LMUSIC_GU IS '음원 장르 코드';
COMMENT ON COLUMN LMUSIC.LMUSIC_GENRE IS '음원 장르명';
COMMENT ON TABLE LPOST IS '홈피게시판 분류 정보';
COMMENT ON COLUMN LPOST.LPOST_GU IS '홈피게시판 분류 코드';
COMMENT ON COLUMN LPOST.LPOST_NO IS '홈피게시판 분류 순번';
COMMENT ON COLUMN LPOST.LPOST_NM IS '홈피게시판 분류 명';
COMMENT ON TABLE MEMBER IS '회원';
COMMENT ON COLUMN MEMBER.MEM_ID IS '회원 ID';
COMMENT ON COLUMN MEMBER.MEM_PASS IS '회원 비밀번호';
COMMENT ON COLUMN MEMBER.MEM_NAME IS '회원 이름';
COMMENT ON COLUMN MEMBER.MEM_NICKNAME IS '회원 닉네임';
COMMENT ON COLUMN MEMBER.MEM_GENDER IS '회원 성별';
COMMENT ON COLUMN MEMBER.MEM_BIR IS '회원 생일';
COMMENT ON COLUMN MEMBER.MEM_ZIP IS '회원 우편번호';
COMMENT ON COLUMN MEMBER.MEM_ADD1 IS '회원 기본 주소';
COMMENT ON COLUMN MEMBER.MEM_ADD2 IS '회원 상세 주소';
COMMENT ON COLUMN MEMBER.MEM_HP IS '회원 이동 전화';
COMMENT ON COLUMN MEMBER.MEM_MAIL IS '회원 이메일 주소';
COMMENT ON COLUMN MEMBER.MEM_CYBERMONEY IS '회원 보유 사이버머니';
COMMENT ON TABLE MESSAGE IS '쪽지';
COMMENT ON COLUMN MESSAGE.MESSAGE_NO IS '쪽지번호 : 쪽지번호';
COMMENT ON COLUMN MESSAGE.MEM_ID IS '회원 ID';
COMMENT ON COLUMN MESSAGE.RECEIVE_MEM IS '받은 회원 : 받은 회원';
COMMENT ON COLUMN MESSAGE.MESSAGE_CONTENT IS '쪽지내용 : 쪽지내용';
COMMENT ON COLUMN MESSAGE.MESSAGE_DATE IS '쪽지날짜 : 쪽지날짜';
COMMENT ON TABLE MINIMI IS '미니미';
COMMENT ON COLUMN MINIMI.MINIMI_ID IS '미니미 ID : 미니미 ID';
COMMENT ON COLUMN MINIMI.LMINIMI_GU IS '미니미 분류 코드 : 미니미 분류 코드';
COMMENT ON COLUMN MINIMI.MINIMI_NAME IS '미니미 명 : 미니미 명';
COMMENT ON COLUMN MINIMI.MINIMI_DESC IS '미니미 설명 : 미니미 설명';
COMMENT ON COLUMN MINIMI.MINIMI_PRICE IS '미니미 가격 : 미니미 가격';
COMMENT ON COLUMN MINIMI.MINIMI_IMG IS '미니미 이미지 : 미니미 이미지';
COMMENT ON COLUMN MINIMI.MINIMI_DETAIL IS '미니미 정보 : 미니미 정보';
COMMENT ON TABLE MINIMI_COLLECTION IS '미니미 보유목록';
COMMENT ON COLUMN MINIMI_COLLECTION.MEM_ID IS '회원 ID';
COMMENT ON COLUMN MINIMI_COLLECTION.MINIMI_ID IS '미니미 ID : 미니미 ID';
COMMENT ON TABLE MUSIC IS '음원';
COMMENT ON COLUMN MUSIC.MUSIC_ID IS '음원 ID';
COMMENT ON COLUMN MUSIC.LMUSIC_GU IS '음원 장르 코드';
COMMENT ON COLUMN MUSIC.MUSIC_TITLE IS '음원 제목';
COMMENT ON COLUMN MUSIC.MUSIC_DESC IS '음원 상세 : 음원 상세';
COMMENT ON COLUMN MUSIC.MUSIC_ARTIST IS '음원 가수';
COMMENT ON COLUMN MUSIC.MUSIC_COMPOSER IS '음원 작곡가';
COMMENT ON COLUMN MUSIC.MUSIC_LYRICIST IS '음원 작사가';
COMMENT ON COLUMN MUSIC.MUSIC_COMPANY IS '음원 제작사';
COMMENT ON COLUMN MUSIC.MUSIC_YEAR IS '음원 제작년도';
COMMENT ON COLUMN MUSIC.MUSIC_ALBUM IS '음원 앨범';
COMMENT ON COLUMN MUSIC.MUSIC_PATH IS '음원 경로 : 음원 경로';
COMMENT ON COLUMN MUSIC.MUSIC_COST IS '음원 가격 : 음원 가격';
COMMENT ON TABLE MUSIC_COLLECTION IS '음반 보유 목록';
COMMENT ON COLUMN MUSIC_COLLECTION.MEM_ID IS '회원 ID';
COMMENT ON COLUMN MUSIC_COLLECTION.MUSIC_ID IS '음원 ID';
COMMENT ON TABLE NOTICE IS '공지게시판';
COMMENT ON COLUMN NOTICE.NOTICE_NO IS '공지게시판 번호';
COMMENT ON COLUMN NOTICE.ADMIN_ID IS '관리자 ID';
COMMENT ON COLUMN NOTICE.NOTICE_TITLE IS '공지게시판 제목';
COMMENT ON COLUMN NOTICE.NOTICE_CONTENT IS '공지게시판 내용';
COMMENT ON COLUMN NOTICE.NOTICE_DATE IS '공지게시글 작성일';
COMMENT ON TABLE POST IS '홈피게시판';
COMMENT ON COLUMN POST.POST_NO IS '홈피게시판 번호';
COMMENT ON COLUMN POST.HOMPI_ID IS '미니홈피 ID';
COMMENT ON COLUMN POST.LPOST_GU IS '홈피게시판 분류 코드';
COMMENT ON COLUMN POST.MEM_ID IS '회원 ID';
COMMENT ON COLUMN POST.POST_TITLE IS '홈피게시판 제목';
COMMENT ON COLUMN POST.POST_CONTENT IS '홈피게시판 내용';
COMMENT ON COLUMN POST.POST_ATTACHMENTS IS '홈피게시판 첨부파일';
COMMENT ON COLUMN POST.POST_DATE IS '게시글 작성일 : 게시글 작성일';
COMMENT ON COLUMN POST.POST_VIEW IS '게시글 조회수 : 게시글 조회수';
COMMENT ON TABLE QNA IS '1대1문의';
COMMENT ON COLUMN QNA.QNA_NO IS '1대1문의 번호';
COMMENT ON COLUMN QNA.MEM_ID IS '회원 ID';
COMMENT ON COLUMN QNA.ADMIN_ID IS '관리자 ID';
COMMENT ON COLUMN QNA.QNA_TITLE IS '1대1문의 제목';
COMMENT ON COLUMN QNA.QNA_CONTENT IS '1대1문의 내용 : 1대1문의 내용';
COMMENT ON COLUMN QNA.QNA_ATTACHMENTS IS '1대1문의 첨부파일 : 1대1문의 첨부파일';
COMMENT ON COLUMN QNA.QNA_DATE IS '1대1문의 작성일 : 1대1문의작성일';
COMMENT ON COLUMN QNA.QNA_RESULT IS '1대1문의 답변 : 1대1문의 답변';
COMMENT ON COLUMN QNA.QNA_CATEGORY IS '1대1문의 카테고리 : 1대1 문의 카테고리';



